"""Initial Migration

Revision ID: 4bdb1b5ae4a0
Revises: 9c2cef0193aa
Create Date: 2019-02-27 12:07:56.420298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdb1b5ae4a0'
down_revision = '9c2cef0193aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'name')
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###
